title: Jekyll Doc Theme
tagline: "The One Place To Learn It All."
description: >- # this means to ignore newlines until "baseurl:"
  All the computer science study material for GATE.
baseurl: "/jekyll-doc-theme"
url: "https://sumeetmathpati.github.io"
author: sumeetmathpati
favicon: "./logo.png" # relative path to site's favicon
logo: "./logo.png"
social:
  name: Sumeet Mathpati
  links:
    - https://www.linkedin.com/in/sumeet221b
    - https://github.com/sumeetmathpati

# Google Analytics
google_analytics: "G-ZGKNYXB78K"

# webmaster_verifications:
#   google: 1234
#   bing: 1234
#   alexa: 1234
#   yandex: 1234
#   baidu: 1234

permalink: /:title/
include: ["_pages"]

# Collections
collections:
  docs:
    output: true

# Default frontmatter
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"
  

# Build settings
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc

# Markdown
markdown: kramdown

kramdown:
  input: GFM
  entity_output: :as_input
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
    